# initial synchronization
/scan_aggregator/duration: 0.2

# scene parsing
/plane_detector_node/scan_range: 5.0
/plane_detector_node/min_intensity: 4500
/layout_extractor_node/min_cluster_size: 1000
/layout_extractor_node/distance_threshold: 0.04
/layout_extractor_node/cluster_tolerance: 0.07
/layout_extractor_node/filter_leaf_size: 0.02

# SLAM
/planar_slam_node/pose_window: 50
/planar_slam_node/sigma_t: 0.01
/planar_slam_node/sigma_d: 0.03
/planar_slam_node/association_range: 0.2

# floorplan estimation
/floorplan_estimation_node/speculation_horizon: 0
/floorplan_estimation_node/min_free_ratio: 0.1
/floorplan_estimation_node/boundary_coverage_threshold: 0.1
/floorplan_estimation_node/boundary_height_threshold: 2.5

# visualization
/floorplan_visualization/draw_graph: false
/floorplan_visualization/boundary_height: 0.3
/layout_cloud_transformer/cloud_window: 20
/object_cloud_transformer/cloud_window: 20