# initial synchronization
/scan_aggregator/duration: 0.2
/scan_aggregator/sensor_calibration: [0.00433407704, 0.99985672803, 0.01636273763, 0.13084133258,
                                      0.99997086446, -0.00443623317, 0.00621209107, -0.05830980169,
                                      0.00628378997, 0.01633533722, -0.99984682363, -0.01167565079,
                                      0.00000000000, 0.00000000000, 0.00000000000, 1.00000000000]

# compass
/point_cloud_compass_node/manhattan_world: true

# scene parsing
/plane_detector_node/scan_range: 10.0
/plane_detector_node/min_intensity: 10000.0
/layout_extractor_node/min_cluster_size: 800
/layout_extractor_node/distance_threshold: 0.08
/layout_extractor_node/cluster_tolerance: 0.15
/layout_extractor_node/filter_leaf_size: 0.02

# SLAM
/planar_slam_node/pose_window: 50
/planar_slam_node/sigma_t: 0.02
/planar_slam_node/sigma_d: 0.04
/planar_slam_node/association_range: 0.3

# floorplan estimation
/floorplan_estimation_node/speculation_horizon: 0
/floorplan_estimation_node/min_free_ratio: 0.0
/floorplan_estimation_node/boundary_coverage_threshold: 1.5
/floorplan_estimation_node/boundary_height_threshold: 2.5
