<?xml version="1.0"?>
<package format="3">
    <name>structural_compass</name>
    <version>0.0.0</version>
    <description>The structural_compass package</description>
    <maintainer email="armon@todo.todo">armon</maintainer>
    <license>TODO</license>

    <buildtool_depend>ament_cmake_ros</buildtool_depend>

    <build_depend>rclcpp</build_depend>
    <build_depend>std_msgs</build_depend>
    <build_depend>sensor_msgs</build_depend>
    <build_depend>nav_msgs</build_depend>
    <build_depend>geometry_msgs</build_depend>
    <build_depend>sbim_msgs</build_depend>
    <build_depend>message_filters</build_depend>
    <build_depend>tf2</build_depend>
    <build_depend>tf2_eigen</build_depend>
    <build_depend>pcl_conversions</build_depend>

    <build_export_depend>rclcpp</build_export_depend>
    <build_export_depend>std_msgs</build_export_depend>
    <build_export_depend>sensor_msgs</build_export_depend>
    <build_export_depend>nav_msgs</build_export_depend>
    <build_export_depend>geometry_msgs</build_export_depend>
    <build_export_depend>sbim_msgs</build_export_depend>
    <build_export_depend>message_filters</build_export_depend>
    <build_export_depend>tf2</build_export_depend>
    <build_export_depend>tf2_eigen</build_export_depend>
    <build_export_depend>pcl_conversions</build_export_depend>

    <exec_depend>rclcpp</exec_depend>
    <exec_depend>std_msgs</exec_depend>
    <exec_depend>sensor_msgs</exec_depend>
    <exec_depend>nav_msgs</exec_depend>
    <exec_depend>sbim_msgs</exec_depend>
    <exec_depend>geometry_msgs</exec_depend>
    <exec_depend>message_filters</exec_depend>
    <exec_depend>tf2</exec_depend>
    <exec_depend>tf2_eigen</exec_depend>
    <exec_depend>pcl_conversions</exec_depend>

    <export>
        <build_type>ament_cmake</build_type>
    </export>

</package>
