<package format="2">
    <name>sbim</name>
    <version>0.1.0</version>
    <description>The sbim package</description>
    
    <maintainer email="armon@todo.todo">armon</maintainer>
    
    <license>TODO</license>

    <buildtool_depend>ament_cmake</buildtool_depend>

    <exec_depend>sbim_msgs</exec_depend>
    <exec_depend>scan_aggregator</exec_depend>
    <exec_depend>structural_compass</exec_depend>
    <exec_depend>floorplan_estimation</exec_depend>
    <exec_depend>planar_slam</exec_depend>
    <exec_depend>sbim_launch</exec_depend>
    <exec_depend>sbim_visualizations</exec_depend>
    <exec_depend>scene_parsing</exec_depend>
    <exec_depend>tf_publishers</exec_depend>
    
    <export>
	    <build_type>ament_cmake</build_type>
    </export>

</package>
